"""empty message

Revision ID: 1fb7089fa3cd
Revises: a746f8f42a4c
Create Date: 2024-09-24 14:22:24.881708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb7089fa3cd'
down_revision = 'a746f8f42a4c'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('comment', sa.Column('rating', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
