"""Add picture column to restaurant

Revision ID: 659b5b4f93d6
Revises: fcd515855dc4
Create Date: 2024-09-17 18:30:29.680359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659b5b4f93d6'
down_revision = 'fcd515855dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
